"""Add category_id to Topic

Revision ID: 719a981bb22c
Revises: 056fed7ca7f9
Create Date: 2025-08-06 01:26:52.256991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719a981bb22c'
down_revision = '056fed7ca7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
